config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/giasu", to: "static_pages#tutor"
  get "/hocsinh", to: "static_pages#student"
  get "/phuhuynh", to: "static_pages#parent"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:destroy, :show]
  resources :tutors, only: [:index, :new, :create, :show]
  resources :students, only: [:new, :create, :show]
  resources :certificates, except: [:index, :show]
  resources :majors, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  resources :schedules, only: [:create, :destroy]
  resources :reports, only: [:create, :destroy] do
    member do
      get :showclass
    end
  end
  resources :posts do
    member do
      get :register
      get :approve
      get :reject
      get :finish
    end
  end

  namespace :admin do
    root "static_pages#index"
    resources :users, except: :show
    resources :subjects, except: :show
    resources :tutors, only: [:index, :show]
    resources :students, only: [:index, :show]
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :gender, presence: true
  validates :dob, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :literacy, presence: true

  scope :newest, ->{order created_at: :desc}

  def review tutor
    review = self.reviews.find_by tutor_id: tutor.id
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < AdminController
  before_action :load_student, only: %i(show)

  def index
    @students = Student.newest
  end

  def show; end

  private

  def load_student
    @student = Student.find_by id: params[:id]
    return if @student
    redirect_to admin_students_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :load_student, only: %i(show)

  def new
    @student = Student.new
  end

  def create
    @student = Student.new student_params
    if @student.save
      flash[:success] = "Bạn đã đăng ký thành công"
      redirect_to @student
    else
      render :new
    end
  end

  def show; end

  private

  def student_params
    params.require(:student).permit :gender, :dob, :phone, :address,
      :literacy, :user_id
  end

  def load_student
    @student = Student.find_by id: params[:id]
    return if @student
    redirect_to current_user
  end
end

app/views/students/_form.html.erb
<div class="login-form">
  <%= form_for @student do |f| %>
    <%= render "shared/error_messages", object: @student %>

    <div class="avatar">
      <%= image_tag("logo.png") %>
    </div>
    <h2 class="text-center">CẬP NHẬP THÔNG TIN CÁ NHÂN</h2>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="form-group">
      <%= f.text_field :phone, class: "form-control", placeholder: "Điện thoại di dộng" %>
    </div>

    <div class="form-group">
      <%= f.text_field :address, class: "form-control", placeholder: "Địa chỉ" %>
    </div>

    <div class="form-group">
      <%= f.date_field :dob, class: "form-control", max: Date.today %>
    </div>

    <div class="row form-group">
      <div class="col-md-3">
        <%= f.radio_button :gender, "Nam" %>
        <%= f.label :gender, "Nam", value: "Nam" %>
      </div>
      <div class="col-md-3">
        <%= f.radio_button :gender, "Nữ" %>
        <%= f.label :gender, "Nữ", value: "Nữ" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.select(:literacy, options_for_student, {:include_blank => "Trình độ học vấn "}, {class: "form-control"}) %>
    </div>

    <div class="form-group">
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-lg btn-block login-btn" %>
    </div>
    <p class="text-center small"><%= link_to "Hủy đăng ký!", user_path(current_user), method: :delete %></p>
  <% end %>
</div>

app/views/students/_student.html.erb
<div class="row">
  <div class="col-md-4 profile">
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-info-circle fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Họ tên đầy đủ</div>
        <p><%= student.user.name %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-calendar fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Ngày tháng năm sinh</div>
        <p><%= student.dob %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-map-marker fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Nơi sống</div>
        <p><%= student.address %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-user fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Giới tính</div>
        <p><%= student.gender %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-graduation-cap fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Trình độ học vấn</div>
        <p><%= student.literacy %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-phone fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Số điện thoại</div>
        <p><%= student.phone %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-envelope fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Email</div>
        <p><%= student.user.email %></p>
      </div>
    </div>
  </div>
  <div class="col-md-8 mentor-info">
    <div class="row">
      <h4 class="mentor-title">Thông tin chung</h4>
    </div>
    <div class="row">
      <h4 class="mentor-title">Bằng cấp</h4>
    </div>
    <div class="row">
      <h4 class="mentor-title">Đánh giá</h4>
    </div>
    <div class="row">
      <h4 class="mentor-title">Bài viết</h4>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<% provide :title, "Đăng ký học sinh" %>
<% provide :button_text, "Đăng ký" %>
<%= render "form" %>

app/views/students/show.html.erb
<% provide(:title, @student.user.name) %>
<div class="row">
  <div class="col-md-4 profile">
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-info-circle fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Họ tên đầy đủ</div>
        <p><%= @student.user.name %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-calendar fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Ngày tháng năm sinh</div>
        <p><%= @student.dob %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-map-marker fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Nơi sống</div>
        <p><%= @student.address %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-user fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Giới tính</div>
        <p><%= @student.gender %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-graduation-cap fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Trình độ học vấn</div>
        <p><%= @student.literacy %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-phone fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Số điện thoại</div>
        <p><%= @student.phone %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-envelope fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Email</div>
        <p><%= @student.user.email %></p>
      </div>
    </div>
  </div>
  <div class="col-md-8 mentor-info">
    <div class="row">
      <h3 class="mentor-title">Bài đăng
        <% if logged_in? && current_user?(@student.user) %>
          <%= link_to "+", new_post_path, class: "button-background" %>
        <% end %>
      </h3>
      <div>
        <ul class="subject-taught">
          <% @student.posts.newest.open.each do |post| %>
            <li>
              <%= link_to post, class: "nav-link cool" do %>
                <%= post.subject.name %> - <%= post.level %> - <%= post.fee.to_i %>/buổi - Ngày bắt đầu: <%= post.from_date %>
              <% end %>

              <% if logged_in? && current_user?(@student.user) %>
                <span style="padding-left: 1em">
                  <%= link_to edit_post_path(post) do %>
                    <em class="fa fa-pencil"></em>
                  <% end %>
                </span>
                <span style="padding-left: 1em">
                  <%= link_to post_path(post), method: :delete, data: {confirm: "Bạn chắc chắn muốn xóa?"} do %>
                    <em class="fa fa-trash"></em>
                  <% end %>
                </span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <% if logged_in? && current_user?(@student.user) %>
      <div class="row">
        <h3 class="mentor-title">Lớp đang đăng ký</h3><br>
        <div>
          <table class="table table-striped table-bordered table-list text-center">
            <thead>
              <tr>
                <th class="text-center">Gia sư</th>
                <th class="text-center">Môn học</th>
                <th class="text-center">Cấp độ</th>
                <th class="text-center"><em class="fa fa-cog"></em></th>
              </tr>
            </thead>
            <tbody>
              <% @student.posts.newest.findStudent.waiting.each do |post| %>
                <tr>
                  <td><%= link_to post.tutor.user.name, tutor_path(post.tutor) %></td>
                  <td><%=  post.subject.name %></td>
                  <td><%=  post.level %></td>
                  <td>
                    <%= link_to post, class: "btn btn-primary" do %>
                      <em class="fa fa-eye"></em>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <h3 class="mentor-title">Yêu cầu dạy của gia sư</h3><br>
        <div>
          <table class="table table-striped table-bordered table-list text-center">
            <thead>
              <tr>
                <th class="text-center">Gia sư</th>
                <th class="text-center">Môn học</th>
                <th class="text-center">Cấp độ</th>
                <th class="text-center"><em class="fa fa-cog"></em></th>
              </tr>
            </thead>
            <tbody>
              <% @student.posts.newest.findTutor.waiting.each do |post| %>
                <tr>
                  <td><%= link_to post.tutor.user.name, tutor_path(post.tutor) %></td>
                  <td><%=  post.subject.name %></td>
                  <td><%=  post.level %></td>
                  <td>
                    <%= link_to approve_post_path(post), class: "btn btn-success" do %>
                      <em class="fa fa-check-circle"></em>
                    <% end %>
                    <%= link_to post, class: "btn btn-primary" do %>
                      <em class="fa fa-eye"></em>
                    <% end %>
                    <%= link_to reject_post_path(post), class: "btn btn-danger" do %>
                      <em class="fa fa-times"></em>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <h3 class="mentor-title">Lớp đang học</h3><br>
        <div>
          <table class="table table-striped table-bordered table-list text-center">
            <thead>
              <tr>
                <th class="text-center">Gia sư</th>
                <th class="text-center">Môn học</th>
                <th class="text-center">Cấp độ</th>
                <th class="text-center"><em class="fa fa-cog"></em></th>
              </tr>
            </thead>
            <tbody>
              <% @student.posts.newest.starting.each do |post| %>
                <tr>
                  <td><%= link_to post.tutor.user.name, tutor_path(post.tutor) %></td>
                  <td><%=  post.subject.name %></td>
                  <td><%=  post.level %></td>
                  <td>
                    <%= link_to showclass_report_path(post), class: "btn btn-primary" do %>
                      <em class="fa fa-eye"></em>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <h3 class="mentor-title">Lịch sử học</h3><br>
        <div>
          <table class="table table-striped table-bordered table-list text-center">
            <thead>
              <tr>
                <th class="text-center">Gia sư</th>
                <th class="text-center">Môn học</th>
                <th class="text-center">Cấp độ</th>
                <th class="text-center">Từ ngày</th>
                <th class="text-center">Đến ngày</th>
                <th class="text-center"><em class="fa fa-cog"></em></th>
              </tr>
            </thead>
            <tbody>
              <% @student.posts.newest.finished.each do |post| %>
                <tr>
                  <td><%= link_to post.tutor.user.name, tutor_path(post.tutor) %></td>
                  <td><%=  post.subject.name %></td>
                  <td><%=  post.level %></td>
                  <td><%=  post.from_date %></td>
                  <td><%=  post.to_date %></td>
                  <td>
                    <%= link_to showclass_report_path(post), class: "btn btn-primary" do %>
                      <em class="fa fa-eye"></em>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>