config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/giasu", to: "static_pages#tutor"
  get "/hocsinh", to: "static_pages#student"
  get "/phuhuynh", to: "static_pages#parent"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:destroy, :show]
  resources :tutors, only: [:index, :new, :create, :show]
  resources :students, only: [:new, :create, :show]
  resources :certificates, except: [:index, :show]
  resources :majors, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  resources :schedules, only: [:create, :destroy]
  resources :reports, only: [:create, :destroy] do
    member do
      get :showclass
    end
  end
  resources :posts do
    member do
      get :register
      get :approve
      get :reject
      get :finish
    end
  end

  namespace :admin do
    root "static_pages#index"
    resources :users, except: :show
    resources :subjects, except: :show
    resources :tutors, only: [:index, :show]
    resources :students, only: [:index, :show]
  end
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :tutor

  validates :school, presence: true
  validates :major, presence: true
  validates :grade, presence: true
  validates :course, presence: true
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :load_certificate, only: %i(edit update destroy)
  def new
    @tutor = current_user.tutor
    @certificate = @tutor.certificates.build
  end

  def create
    @certificate = current_user.tutor.certificates.build certificate_params
    if @certificate.save
      flash[:success] = "Cập nhật thành công"
      redirect_to @certificate.tutor
    else
      @tutor = current_user.tutor
      render :new
    end
  end

  def edit
    @tutor = current_user.tutor
  end

  def update
    if @certificate.update_attributes certificate_params
      flash[:success] = "Cập nhật thành công"
      redirect_to current_user.tutor
    else
      @tutor = current_user.tutor
      render :edit
    end
  end

  def destroy
    if @certificate.destroy
      flash[:success] = "Bạn đã xóa thành công"
    else
      flash[:danger] = "Có lỗi khi xóa. Vui lòng thử lại"
    end
    redirect_to current_user.tutor
  end

  private

  def certificate_params
    params.require(:certificate).permit :school, :major, :grade, :course
  end

  def load_certificate
    @certificate = Certificate.find_by id: params[:id]
    return if @certificate
    redirect_to current_user.tutor
  end
end

app/views/certificates/_certificate.html.erb
<li><%= certificate.school %>
  <% if logged_in? && current_user?(@tutor.user) %>
    <span style="padding-left: 1em">
      <%= link_to edit_certificate_path(certificate) do %>
        <em class="fa fa-pencil"></em>
      <% end %>
    </span>

    <span style="padding-left: 1em">
      <%= link_to certificate_path(certificate), method: :delete, data: {confirm: "Bạn chắc chắn muốn xóa?"} do %>
        <em class="fa fa-trash"></em>
      <% end %>
    </span>
  <% end %>
  <div style="padding-left: 2em; padding-top: 0.5em">
    Chuyên ngành <b style="color: black"><%= certificate.major %></b>
  </div>
  <div style="padding-left: 2em; padding-top: 0.5em">
    Khóa học <b style="color: black"><%= certificate.course %></b>
  </div>
  <div style="padding-left: 2em; padding-top: 0.5em">
    Xếp loại <b style="color: black"><%= certificate.grade %></b>
  </div>
</li>

app/views/certificates/_form.html.erb
<%= form_for  @certificate do |f| %>
  <%= render "shared/error_messages", object: @certificate %>

  <div class="form-group">
    <%= f.text_field :school, class: "form-control", placeholder: "Tên trường" %>
  </div>

  <div class="form-group">
    <%= f.text_field :major, class: "form-control", placeholder: "Chuyên ngành" %>
  </div>

  <div class="form-group">
    <%= f.text_field :grade, class: "form-control", placeholder: "Xếp loại" %>
  </div>

  <div class="form-group">
    <%= f.text_field :course, class: "form-control", placeholder: "Khóa học" %>
  </div>

  <div class="form-group">
    <%= f.submit "Cập nhật", class: "button-background" %>
    <%= link_to "Trở lại", current_user.tutor, class: "button-background" %>
  </div>
<% end %>

app/views/certificates/new.html.erb
<% provide(:title, @tutor.user.name) %>
<div class="row">
  <div class="col-md-4 profile">
    <div class="row mentor-avatar">
      <%= image_tag @tutor.avatar_url.to_s %>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-info-circle fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Họ tên đầy đủ</div>
        <p><%= @tutor.user.name %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-calendar fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Ngày tháng năm sinh</div>
        <p><%= @tutor.dob %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-map-marker fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Nơi sống</div>
        <p><%= @tutor.address %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-user fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Giới tính</div>
        <p><%= @tutor.gender %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-graduation-cap fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Trình độ học vấn</div>
        <p><%= @tutor.literacy %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-phone fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Số điện thoại</div>
        <p><%= @tutor.phone %></p>
      </div>
    </div>
    <div class="row info">
      <div class="col-md-2"><i class="fa fa-envelope fa-2x"></i></div>
      <div class="col-md-9">
        <div class="title">Email</div>
        <p><%= @tutor.user.email %></p>
      </div>
    </div>
  </div>
  <div class="col-md-8 mentor-info">
    <h3 class="text-center">Cập nhật thông tin bằng cấp</h3><br>
    <%= render "form" %>
  </div>
</div>