config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/giasu", to: "static_pages#tutor"
  get "/hocsinh", to: "static_pages#student"
  get "/phuhuynh", to: "static_pages#parent"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:destroy, :show]
  resources :tutors, only: [:index, :new, :create, :show]
  resources :students, only: [:new, :create, :show]
  resources :certificates, except: [:index, :show]
  resources :majors, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  resources :schedules, only: [:create, :destroy]
  resources :reports, only: [:create, :destroy] do
    member do
      get :showclass
    end
  end
  resources :posts do
    member do
      get :register
      get :approve
      get :reject
      get :finish
    end
  end

  namespace :admin do
    root "static_pages#index"
    resources :users, except: :show
    resources :subjects, except: :show
    resources :tutors, only: [:index, :show]
    resources :students, only: [:index, :show]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :tutor, optional: true
  belongs_to :student, optional: true
  belongs_to :subject
  has_many :reports, dependent: :destroy
  has_many :schedules, dependent: :destroy

  validates :level, presence: true
  validates :title, presence: true
  validates :from_date, presence: true
  validates :fee, presence: true, numericality: {only_float: true}

  enum status: {open: 0, waiting: 1,starting: 2, finished: 3}

  scope :newest, ->{order created_at: :desc}
  scope :findTutor, ->{where(brand: "Trò Tìm Gia Sư")}
  scope :findStudent, ->{where(brand: "Gia Sư Tìm Trò")}

  def ofTutor?
    brand == "Gia Sư Tìm Trò"
  end

  def address
    if ofTutor?
      tutor.address
    else
      student.address
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: %i(show edit update destroy register approve reject finish)

  def index
    @posts = Post.newest.open
    if params[:search]
      if params[:search][:subject_id] != ""
        @posts = @posts.where subject_id: params[:search][:subject_id]
      end
      if params[:search][:level] != ""
        @posts = @posts.where level: params[:search][:level]
      end
      if params[:search][:brand] != ""
        @posts = @posts.where brand: params[:search][:brand]
      end
      if params[:search][:address] != ""
        @posts = @posts.select{ |p| p.address == params[:search][:address]}
      end
    end
  end

  def new
    if current_user.tutor?
      @post = current_user.tutor.posts.build
    else
      @post = current_user.student.posts.build
    end
  end

  def create
    if current_user.tutor?
      @post = current_user.tutor.posts.build post_params
    else
      @post = current_user.student.posts.build post_params
    end
    if @post.save
      flash[:success] = "Cập nhật thành công"
      redirect_to @post
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update_attributes post_params
      flash[:success] = "Cập nhật thành công"
      if @post.starting?
        redirect_to showclass_report_path(@post)
      else
        redirect_to @post
      end
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Bạn đã xóa thành công"
    else
      flash[:danger] = "Có lỗi khi xóa. Vui lòng thử lại"
    end
    redirect_to current_user
  end

  def register
    if @post.ofTutor?
      if current_user.tutor? || current_user.admin?
        flash[:danger] = "Bạn không thể đăng ký học lớp này"
        redirect_to @post
      else
        @post.update_attributes status: 1, student_id: current_user.student.id
        flash[:success] = "Đăng ký thành công, chờ phê duyệt...!"
        redirect_to current_user
      end
    else
      if current_user.student? || current_user.admin?
        flash[:danger] = "Bạn không thể đăng ký dạy lớp này"
        redirect_to @post
      else
        @post.update_attributes status: 1, tutor_id: current_user.tutor.id
        flash[:success] = "Đăng ký thành công, chờ phê duyệt...!"
        redirect_to current_user
      end
    end
  end

  def approve
    @post.update_attributes status: 2
    flash[:success] = "Bạn đã phê duyệt yêu cầu"
    redirect_to current_user
  end

  def reject
    if @post.ofTutor?
      @post.update_attributes status: 0, student_id: nil
    else
      @post.update_attributes status: 0, tutor_id: nil
    end
    flash[:success] = "Bạn đã từ chối yêu cầu"
    redirect_to current_user
  end

  def finish
    @post.update_attributes status: 3, to_date: Date.current
    flash[:success] = "Bạn đã kết thúc lớp học"
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit :subject_id, :level, :title, :fee, :from_date, :brand
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    redirect_to current_user
  end
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= render "shared/error_messages", object: @post %>

  <% if current_user.tutor? %>
    <%= f.hidden_field :brand, value: "Gia Sư Tìm Trò" %>
  <% else %>
    <%= f.hidden_field :brand, value: "Trò Tìm Gia Sư" %>
  <% end%>

  <div class="form-group">
    <% if current_user.tutor? %>
      <%= f.select(:subject_id, current_user.tutor.select_subject,
        {:include_blank => "Chọn môn dạy"}, {class: "form-control"}) %>
    <% else %>
      <%= f.select(:subject_id, select_subject, {:include_blank => "Chọn môn dạy"}, {class: "form-control"}) %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.select(:level, options_for_student, {:include_blank => "Chọn cấp độ"}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Tiêu đề" %>
  </div>

  <div class="form-group">
    <%= f.number_field :fee, class: "form-control", placeholder: "Học phí", min: 0 %>
  </div>

  <div class="form-group">
    <%= f.date_field :from_date, class: "form-control", min: Date.today %>
  </div>

  <div class="form-group">
    <%= f.submit "Cập nhật", class: "button-background" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row" id="post">
  <div class="col-md-12">
    <%= link_to post, class: "col-md-8 nav-link cool title" do %>
      [<%= post.brand %>] <%=post.title %>
    <% end %>
  </div>
  <div class="col-md-12">
    <div class="col-md-4">
      <p><i class="fa fa-user"></i> <%= post.ofTutor? ? post.tutor.user.name : post.student.user.name %></p>
      <p><i class="fa fa-calendar"></i> <%= post.created_at.strftime("%F") %></p>
    </div>
    <div class="col-md-4">
      <p><i class="fa fa-book"></i> Môn học: <%= post.subject.name %></p>
      <p><i class="fa fa-graduation-cap"></i> Cấp độ: <%= post.level %></p>
    </div>
    <div class="col-md-4">
      <p><i class="fa fa-money"></i> Học phí: <%= post.fee.to_i %>/buổi</p>
      <p><i class="fa fa-map-marker"></i> Địa chỉ: <%= post.ofTutor? ? post.tutor.address : post.student.address %></p>
    </div>
  </div>
  <div class="col-md-12">
    <div class="col-md-12">
      <% if logged_in?  %>
        <%= link_to register_post_path(post) do %>
          <button class="button-background">Đăng ký <%= post.ofTutor? ? "học" : "dạy" %></button>
        <% end %>
      <% else %>
        <%= link_to login_path do %>
          <button class="button-background">Đăng ký <%= post.ofTutor? ? "học" : "dạy" %></button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<%= form_for(:search, url: posts_path, :html => { :method => "GET" }) do |f| %>
  <div class="col-md-10">
    <div class="row">
      <div class="col-md-3 form-group">
        <%= f.select(:address, (select_address_tutor + select_address_student).uniq,
          {:include_blank => "Địa chỉ"}, {class: "form-control"}) %>
      </div>

      <div class="col-md-3 form-group">
        <%= f.select(:subject_id, select_subject,
          {:include_blank => "Môn học"}, {class: "form-control"}) %>
      </div>

      <div class="col-md-3 form-group">
        <%= f.select(:level, options_for_student,
          {:include_blank => "Cấp độ"}, {class: "form-control"}) %>
      </div>

      <div class="col-md-3 form-group">
        <%= f.select(:brand, select_brand,
          {:include_blank => "Hình thức"}, {class: "form-control"}) %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="col-md-12 form-group">
      <%= f.submit "Tìm kiếm",class: "button-background" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Cập nhật thông tin khóa học") %>
<div class="col-md-8 col-md-offset-2 mentor-info">
  <h3 class="text-center">Cập nhật thông tin khóa học</h3><br>
  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<% provide :title, "Danh sách lớp hiện có" %>
<h1 class="tns-title">Danh sách lớp hiện có</h1>
<hr>
<div class="row">
  <%= render "search" %>
</div>
<div class="row">
  <% if params[:search] %>
    <div class="col-md-12">
      <p><i>Có <%= @posts.count %> lớp
        <%= params[:search][:address] != "" ? "ở #{params[:search][:address]}" : "" %>
        <%= params[:search][:subject_id] != "" ? "- #{Subject.find(params[:search][:subject_id]).name}" : "" %>
        <%= params[:search][:level] != "" ? "- #{params[:search][:level]}" : "" %>
        <%= params[:search][:brand] != "" ? "[#{params[:search][:brand]}]" : "" %>
      </i></p><br>
    </div>
  <% end %>
</div>
<div class="row">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Cập nhật thông tin khóa học") %>
<div class="col-md-8 col-md-offset-2 mentor-info">
  <h3 class="text-center">Cập nhật thông tin khóa học</h3><br>
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="row mentor-info show-post">
  <div class="col-md-12 created_at">Ngày đăng: <%= @post.created_at.strftime("%F") %></div>

  <div class="col-md-4 info">
    <h3>Thông tin người đăng</h3>
    <ul>
      <div class="user">
        <i class="fa fa-user"></i> <%= @post.ofTutor? ? @post.tutor.user.name : @post.student.user.name %>
      </div>
      <div class="user">
        <i class="fa fa-calendar"></i> <%= @post.ofTutor? ? @post.tutor.dob : @post.student.dob %>
      </div>
      <div class="user">
        <i class="fa fa-phone"></i> <%= @post.ofTutor? ? @post.tutor.phone : @post.student.phone %>
      </div>
      <div class="user">
        <i class="fa fa-map-marker"></i> <%= @post.ofTutor? ? @post.tutor.address : @post.student.address %>
      </div>
      <div class="user">
        <i class="fa fa-graduation-cap"></i> <%= @post.ofTutor? ? @post.tutor.literacy : @post.student.literacy %>
      </div>
      <div class="user">
        <i class="fa fa-envelope"></i> <%= @post.ofTutor? ? @post.tutor.user.email : @post.student.user.email %>
      </div>
      <% if @post.ofTutor? %>
        <div class="user"><%= link_to "Xem chi tiết gia sư", @post.tutor %></div>
      <% end %>
    </ul>
  </div>

  <div class="col-md-4 info">
    <h3>Thông tin lớp học</h3>
    <ul>
      <div class="user"><i class="fa fa-flag-checkered"></i> <%= @post.title %></div>
      <div class="user"><i class="fa fa-book"></i> <%= @post.subject.name %></div>
      <div class="user"><i class="fa fa-graduation-cap"></i> <%= @post.level %></div>
      <div class="user"><i class="fa fa-money"></i> <%= @post.fee.to_i %>/buổi</div>
      <div class="user created_at">Dự kiến bắt đầu: <%= @post.from_date %></div>
    </ul>
  </div>

  <div class="col-md-4 info">
    <h3>Lịch học dự kiến
      <% if logged_in? && current_user?(@post.ofTutor? ? @post.tutor.user : @post.student.user) %>
        <!-- Button trigger modal -->
        <button type="button" class="button-background" data-toggle="modal" data-target="#schedules">+</button>
        <!-- Modal -->
        <div class="modal fade" id="schedules" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Thêm lịch học</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render "schedules/form" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </h3>
    <div>
      <ul class="subject-taught">
        <%= render @post.schedules %>
      </ul>
    </div>
  </div>

  <div class="col-md-12">
    <% if logged_in? %>
      <% if @post.open? %>
        <%= link_to register_post_path(@post) do %>
          <button class="button-background">Đăng ký <%= @post.ofTutor? ? "học" : "dạy" %></button>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to login_path do %>
        <button class="button-background">Đăng ký <%= @post.ofTutor? ? "học" : "dạy" %></button>
      <% end %>
    <% end %>
  </div>
</div>