config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/giasu", to: "static_pages#tutor"
  get "/hocsinh", to: "static_pages#student"
  get "/phuhuynh", to: "static_pages#parent"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:destroy, :show]
  resources :tutors, only: [:index, :new, :create, :show]
  resources :students, only: [:new, :create, :show]
  resources :certificates, except: [:index, :show]
  resources :majors, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]
  resources :schedules, only: [:create, :destroy]
  resources :reports, only: [:create, :destroy] do
    member do
      get :showclass
    end
  end
  resources :posts do
    member do
      get :register
      get :approve
      get :reject
      get :finish
    end
  end

  namespace :admin do
    root "static_pages#index"
    resources :users, except: :show
    resources :subjects, except: :show
    resources :tutors, only: [:index, :show]
    resources :students, only: [:index, :show]
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :post

  validates :study_date, presence: true
  validates :content, presence: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :load_post, only: %i(showclass)
  before_action :load_report, only: %i(destroy)

  def showclass; end

  def create
    @report = Report.new report_params
    if @report.save
      flash[:success] = "Cập nhật thành công"
    else
      flash[:danger] = "Cập nhật thất bại"
    end
    redirect_to showclass_report_path(@report.post)
  end

  def destroy
    if @report.destroy
      flash[:success] = "Bạn đã xóa thành công"
    else
      flash[:danger] = "Có lỗi khi xóa. Vui lòng thử lại"
    end
    redirect_to showclass_report_path(@report.post)
  end

  private

  def report_params
    params.require(:report).permit :post_id, :study_date, :content
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    redirect_to current_user
  end

  def load_report
    @report = Report.find_by id: params[:id]
    return if @report
    redirect_to current_user
  end
end

app/views/reports/_form.html.erb
<%= form_for Report.new do |f| %>

  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :study_date, value: Date.current %>

  <div class="form-group">
    <%= f.text_area :content, class: "form-control", placeholder: "Nội dung" %>
  </div>

  <div class="form-group">
    <%= f.submit "Cập nhật", class: "button-background" %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<li><%= report.study_date %>
  <% if logged_in? && current_user?(report.post.tutor.user) && report.post.starting? %>
    <span style="padding-left: 1em">
      <%= link_to report_path(report), method: :delete, data: {confirm: "Bạn chắc chắn muốn xóa?"} do %>
        <em class="fa fa-trash"></em>
      <% end %>
    </span>
  <% end %>
  <p style="padding-left: 1em; padding-top: 0.5em;"><%= report.content %></p>
</li>

app/views/reports/showclass.html.erb
<% provide(:title, @post.title) %>
<div class="row mentor-info show-post">
  <div class="col-md-4 info">
    <h3>Thông tin gia sư</h3>
    <ul>
      <div class="user">
        <i class="fa fa-user"></i> <%= @post.tutor.user.name %>
      </div>
      <div class="user">
        <i class="fa fa-calendar"></i> <%= @post.tutor.dob %>
      </div>
      <div class="user">
        <i class="fa fa-phone"></i> <%= @post.tutor.phone %>
      </div>
      <div class="user">
        <i class="fa fa-map-marker"></i> <%= @post.tutor.address %>
      </div>
      <div class="user">
        <i class="fa fa-graduation-cap"></i> <%= @post.tutor.literacy %>
      </div>
      <div class="user">
        <i class="fa fa-envelope"></i> <%= @post.tutor.user.email %>
      </div>
      <div class="user">
        <%= link_to "Xem chi tiết gia sư", @post.tutor %>
      </div>
    </ul>
  </div>

  <div class="col-md-4 info">
    <h3>Thông tin lớp học
      <% if logged_in? && current_user?(@post.tutor.user) && @post.starting? %>
        <%= link_to edit_post_path(@post), class: "button-background" do %>
          <i class="fa fa-pencil"></i>
        <% end %>
      <% end %>
    </h3>
    <ul>
      <div class="user"><i class="fa fa-flag-checkered"></i> <%= @post.title %></div>
      <div class="user"><i class="fa fa-book"></i> <%= @post.subject.name %></div>
      <div class="user"><i class="fa fa-graduation-cap"></i> <%= @post.level %></div>
      <div class="user"><i class="fa fa-money"></i> <%= @post.fee.to_i %>/buổi</div>
      <div class="user"><i class="fa fa-calendar"></i> Bắt đầu: <%= @post.from_date %></div>
      <div class="user"><i class="fa fa-calendar"></i> Kết thúc: <%= @post.to_date %></div>
      <% if @post.starting? %>
        <% if current_user?(@post.tutor.user) %>
          <div class="user"><%= link_to "KẾT THÚC",finish_post_path(@post), class: "button-background" %></div>
        <% end %>
      <% else %>
        <button class="button-background">ĐÃ KẾT THÚC</button>
      <% end %>
    </ul>
  </div>

  <div class="col-md-4 info">
    <h3>Thông tin học sinh</h3>
    <ul>
      <div class="user">
        <i class="fa fa-user"></i> <%= @post.student.user.name %>
      </div>
      <div class="user">
        <i class="fa fa-calendar"></i> <%= @post.student.dob %>
      </div>
      <div class="user">
        <i class="fa fa-phone"></i> <%= @post.student.phone %>
      </div>
      <div class="user">
        <i class="fa fa-map-marker"></i> <%= @post.student.address %>
      </div>
      <div class="user">
        <i class="fa fa-graduation-cap"></i> <%= @post.student.literacy %>
      </div>
      <div class="user">
        <i class="fa fa-envelope"></i> <%= @post.student.user.email %>
      </div>
      <div class="user">
        <%= link_to "Xem chi tiết học sinh", @post.student %>
      </div>
    </ul>
  </div>
</div>
<br>
<div class="row mentor-info show-post">
  <div class="col-md-4 info">
    <h3>Lịch học
      <% if logged_in? && current_user?(@post.tutor.user) && @post.starting? %>
        <!-- Button trigger modal -->
        <button type="button" class="button-background" data-toggle="modal" data-target="#schedules">+</button>
        <!-- Modal -->
        <div class="modal fade" id="schedules" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Thêm lịch học</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render "schedules/form" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </h3>
    <div>
      <ul class="subject-taught">
        <%= render @post.schedules %>
      </ul>
    </div>
  </div>
  <div class="col-md-8 info">
    <h3>Sổ liên lạc
      <% if logged_in? && current_user?(@post.tutor.user) && @post.starting? %>
        <!-- Button trigger modal -->
        <button type="button" class="button-background" data-toggle="modal" data-target="#reports">+</button>
        <!-- Modal -->
        <div class="modal fade" id="reports" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Nhận xét của gia sư</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render "reports/form" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </h3>
    <div>
      <ul class="subject-taught">
        <%= render @post.reports.newest %>
      </ul>
    </div>
  </div>
</div>